### ISSUE TITLE
Issues running your configuration on FLSun QQ-S Pro

### ISSUE THREAD

**Issue by mifrendjim** [CobraPi/Klipper-Firmware-FLSUN-QQ-S-Pro#8]
I followed your guide, and so far I'm having issues with the steppers A, B, C. 

I'm getting a ton of vibration from the stock motors.
Only 2 of the 3 arms are homing correctly, only 2/3 are hitting the end stops.
When I try to test extrude Klipper looks like it's crashing, or the firmware is crashing.
Klipper is also not allowing me to move the gantry around using the controls. It sends the command but returns 
`Move out of range: 0.000 10.000 370.010 [0.000]`

I had to update the printer.cfg so all the stepper blocks had:
`position_endstop: 370
 arm_length: 280.0`

Did you run into any of these issues? I've attached my config.
[printer.txt](https://github.com/CobraPi/Klipper-Firmware-FLSUN-QQ-S-Pro-Delta-Printer/files/7493138/printer.txt)

**Comment by conlank** [comment]
Post the klipper.log

**Comment by mifrendjim** [comment]
`===== Config file =====
[mcu]
serial = /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0
restart_method = command
baud = 250000

[printer]
kinematics = delta
max_velocity = 500
max_accel = 2000
max_z_velocity = 200
minimum_z_position = -5
delta_radius = 130

[stepper_a]
step_pin = PE3
dir_pin = PE2
enable_pin = !PE4
rotation_distance = 32
endstop_pin = PA15
microsteps = 16
homing_speed = 20
position_endstop = 370
arm_length = 280.0

[stepper_b]
step_pin = PE0
dir_pin = PB9
enable_pin = !PE1
rotation_distance = 32
endstop_pin = PA12
microsteps = 16
homing_speed = 20
position_endstop = 370
arm_length = 280.0

[stepper_c]
step_pin = PB5
dir_pin = PB4
enable_pin = !PB8
rotation_distance = 32
endstop_pin = PC4
microsteps = 16
homing_speed = 20
position_endstop = 370
arm_length = 280.0

[probe]
pin = !PA11
x_offset = 0
y_offset = 0
z_offset = 10
samples = 3
samples_result = average
sample_retract_dist = 5

[delta_calibrate]
radius = 120
horizontal_move_z = 10

[extruder]
step_pin = PD6
dir_pin = !PD3
enable_pin = !PB3
rotation_distance = 9
microsteps = 16
nozzle_diameter = 0.400
filament_diameter = 1.750
heater_pin = PC3
sensor_type = EPCOS 100K B57560G104F
sensor_pin = PC1
control = pid
pid_kp = 14.529
pid_ki = 0.557
pid_kd = 94.802
min_extrude_temp = 180
min_temp = 0
max_temp = 260

[heater_bed]
heater_pin = PA0
sensor_type = EPCOS 100K B57560G104F
sensor_pin = PC0
control = pid
pid_kp = 325.10
pid_ki = 63.35
pid_kd = 417.10
min_temp = 0
max_temp = 150

[fan]
pin = PB1
kick_start_time = 0.200

[virtual_sdcard]
path = ~/gcode_files

[display_status]

[pause_resume]

[gcode_macro START_PRINT]
gcode = 

[gcode_macro END_PRINT]
gcode = 
	SET_GCODE_OFFSET Z_ADJUST=0

[gcode_macro PAUSE]
rename_existing = BASE_PAUSE
gcode = 
	SAVE_GCODE_STATE NAME=PAUSE_state
	BASE_PAUSE
	G91
	G1 E-{E} F2100
	G1 Z{Z}
	G90
	G1 X{X} Y{Y} F6000

[gcode_macro RESUME]
rename_existing = BASE_RESUME
gcode = 
	G91
	G1 E{E} F2100
	G90
	RESTORE_GCODE_STATE NAME=PAUSE_state MOVE=1
	BASE_RESUME

[gcode_macro CANCEL_PRINT]
rename_existing = BASE_CANCEL_PRINT
gcode = 
	TURN_OFF_HEATERS
	CLEAR_PAUSE
	SDCARD_RESET_FILE
	BASE_CANCEL_PRINT
=======================
Args: ['/home/pi/klipper/klippy/klippy.py', '/home/pi/klipper_config/printer.cfg', '-l', '/home/pi/klipper_logs/klippy.log', '-a', '/tmp/klippy_uds']
Git version: 'v0.10.0-113-gd4aee4f5'
CPU: 4 core ARMv7 Processor rev 4 (v7l)
Python: '2.7.16 (default, Oct 10 2019, 22:02:15) \n[GCC 8.3.0]'
webhooks client 1968411672: {'program': 'Moonraker', 'version': 'v0.7.1-41-g2450534'}
=============== Log rollover at Wed Nov 10 00:05:37 2021 ===============
mcu 'mcu': Unable to open serial port: [Errno 2] could not open port /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0'
mcu 'mcu': Unable to open serial port: [Errno 2] could not open port /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0'
mcu 'mcu': Unable to open serial port: [Errno 2] could not open port /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0'
mcu 'mcu': Unable to open serial port: [Errno 2] could not open port /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0'
mcu 'mcu': Unable to open serial port: [Errno 2] could not open port /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0'
mcu 'mcu': Unable to open serial port: [Errno 2] could not open port /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0'
mcu 'mcu': Unable to open serial port: [Errno 2] could not open port /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0'
mcu 'mcu': Unable to open serial port: [Errno 2] could not open port /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0'
mcu 'mcu': Unable to open serial port: [Errno 2] could not open port /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0'
mcu 'mcu': Unable to open serial port: [Errno 2] could not open port /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0'
mcu 'mcu': Unable to open serial port: [Errno 2] could not open port /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0'
mcu 'mcu': Unable to open serial port: [Errno 2] could not open port /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0'
MCU error during connect
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/klippy.py", line 158, in _connect
    self.send_event("klippy:mcu_identify")
  File "/home/pi/klipper/klippy/klippy.py", line 248, in send_event
    return [cb(*params) for cb in self.event_handlers.get(event, [])]
  File "/home/pi/klipper/klippy/mcu.py", line 765, in _mcu_identify
    raise error(str(e))
error: mcu 'mcu': Unable to connect
Build file /home/pi/klipper/klippy/../.config(2497): Sun Nov  7 20:48:23 2021
========= Last MCU build config =========
CONFIG_LOW_LEVEL_OPTIONS=y
# CONFIG_MACH_AVR is not set
# CONFIG_MACH_ATSAM is not set
# CONFIG_MACH_ATSAMD is not set
# CONFIG_MACH_LPC176X is not set
CONFIG_MACH_STM32=y
# CONFIG_MACH_RP2040 is not set
# CONFIG_MACH_PRU is not set
# CONFIG_MACH_LINUX is not set
# CONFIG_MACH_SIMU is not set
CONFIG_BOARD_DIRECTORY="stm32"
CONFIG_MCU="stm32f103xe"
CONFIG_CLOCK_FREQ=72000000
CONFIG_SERIAL=y
CONFIG_FLASH_START=0x8007000
CONFIG_FLASH_SIZE=0x10000
CONFIG_RAM_START=0x20000000
CONFIG_RAM_SIZE=0x5000
CONFIG_STACK_SIZE=512
CONFIG_STM32_SELECT=y
CONFIG_MACH_STM32F103=y
# CONFIG_MACH_STM32F207 is not set
# CONFIG_MACH_STM32F401 is not set
# CONFIG_MACH_STM32F405 is not set
# CONFIG_MACH_STM32F407 is not set
# CONFIG_MACH_STM32F429 is not set
# CONFIG_MACH_STM32F446 is not set
# CONFIG_MACH_STM32F031 is not set
# CONFIG_MACH_STM32F042 is not set
# CONFIG_MACH_STM32F070 is not set
# CONFIG_MACH_STM32F072 is not set
# CONFIG_MACH_STM32H750 is not set
CONFIG_MACH_STM32F1=y
CONFIG_HAVE_STM32_USBFS=y
CONFIG_HAVE_STM32_CANBUS=y
# CONFIG_STM32_FLASH_START_2000 is not set
# CONFIG_STM32_FLASH_START_5000 is not set
CONFIG_STM32_FLASH_START_7000=y
# CONFIG_STM32_FLASH_START_8000 is not set
# CONFIG_STM32_FLASH_START_8800 is not set
# CONFIG_STM32_FLASH_START_10000 is not set
# CONFIG_STM32_FLASH_START_800 is not set
# CONFIG_STM32_FLASH_START_4000 is not set
# CONFIG_STM32_FLASH_START_0000 is not set
CONFIG_STM32_CLOCK_REF_8M=y
# CONFIG_STM32_CLOCK_REF_12M is not set
# CONFIG_STM32_CLOCK_REF_16M is not set
# CONFIG_STM32_CLOCK_REF_25M is not set
# CONFIG_STM32_CLOCK_REF_INTERNAL is not set
CONFIG_CLOCK_REF_FREQ=8000000
CONFIG_STM32F0_TRIM=16
# CONFIG_STM32_USB_PA11_PA12 is not set
# CONFIG_STM32_SERIAL_USART1 is not set
# CONFIG_STM32_SERIAL_USART1_ALT_PB7_PB6 is not set
# CONFIG_STM32_SERIAL_USART2 is not set
# CONFIG_STM32_SERIAL_USART2_ALT_PD6_PD5 is not set
CONFIG_STM32_SERIAL_USART3=y
# CONFIG_STM32_SERIAL_USART3_ALT_PD9_PD8 is not set
# CONFIG_STM32_CANBUS_PA11_PA12 is not set
# CONFIG_STM32_CANBUS_PB8_PB9 is not set
CONFIG_CANBUS_FREQUENCY=500000
CONFIG_SERIAL_BAUD=250000
CONFIG_USB_VENDOR_ID=0x1d50
CONFIG_USB_DEVICE_ID=0x614e
CONFIG_USB_SERIAL_NUMBER_CHIPID=y
CONFIG_USB_SERIAL_NUMBER="12345"
CONFIG_INITIAL_PINS=""
CONFIG_HAVE_GPIO=y
CONFIG_HAVE_GPIO_ADC=y
CONFIG_HAVE_GPIO_SPI=y
CONFIG_HAVE_GPIO_I2C=y
CONFIG_HAVE_GPIO_HARD_PWM=y
CONFIG_HAVE_GPIO_BITBANGING=y
CONFIG_HAVE_STRICT_TIMING=y
CONFIG_HAVE_CHIPID=y
CONFIG_HAVE_STEPPER_BOTH_EDGE=y
CONFIG_INLINE_STEPPER_HACK=y
=======================
Build file /home/pi/klipper/klippy/../out/klipper.dict(6839): Sun Nov  7 20:49:03 2021
Last MCU build version: v0.10.0-113-gd4aee4f5
Last MCU build tools: gcc: (15:7-2018-q2-6) 7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907] binutils: (2.31.1-11+rpi1+11) 2.31.1
Last MCU build config: BUS_PINS_i2c1=PB6,PB7 RECEIVE_WINDOW=192 RESERVE_PINS_serial=PB11,PB10 BUS_PINS_i2c2=PB10,PB11 BUS_PINS_i2c1a=PB8,PB9 STEPPER_BOTH_EDGE=1 SERIAL_BAUD=250000 ADC_MAX=4095 BUS_PINS_spi3=PB4,PB5,PB3 BUS_PINS_spi2=PB14,PB15,PB13 BUS_PINS_spi1=PA6,PA7,PA5 PWM_MAX=255 MCU=stm32f103xe STATS_SUMSQ_BASE=256 BUS_PINS_spi1a=PB4,PB5,PB3 CLOCK_FREQ=72000000
Build file /home/pi/klipper/klippy/../out/klipper.elf(251836): Sun Nov  7 20:49:17 2021
Starting Klippy...
Args: ['/home/pi/klipper/klippy/klippy.py', '/home/pi/klipper_config/printer.cfg', '-l', '/home/pi/klipper_logs/klippy.log', '-a', '/tmp/klippy_uds']
Git version: 'v0.10.0-113-gd4aee4f5'
CPU: 4 core ARMv7 Processor rev 4 (v7l)
Python: '2.7.16 (default, Oct 10 2019, 22:02:15) \n[GCC 8.3.0]'
Start printer at Wed Nov 10 00:07:21 2021 (1636502841.5 22.0)
===== Config file =====
[mcu]
serial = /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0
restart_method = command
baud = 250000

[printer]
kinematics = delta
max_velocity = 500
max_accel = 2000
max_z_velocity = 200
minimum_z_position = -5
delta_radius = 130

[stepper_a]
step_pin = PE3
dir_pin = PE2
enable_pin = !PE4
rotation_distance = 32
endstop_pin = PA15
microsteps = 16
homing_speed = 20
position_endstop = 370
arm_length = 280.0

[stepper_b]
step_pin = PE0
dir_pin = PB9
enable_pin = !PE1
rotation_distance = 32
endstop_pin = PA12
microsteps = 16
homing_speed = 20
position_endstop = 370
arm_length = 280.0

[stepper_c]
step_pin = PB5
dir_pin = PB4
enable_pin = !PB8
rotation_distance = 32
endstop_pin = PC4
microsteps = 16
homing_speed = 20
position_endstop = 370
arm_length = 280.0

[probe]
pin = !PA11
x_offset = 0
y_offset = 0
z_offset = 10
samples = 3
samples_result = average
sample_retract_dist = 5

[delta_calibrate]
radius = 120
horizontal_move_z = 10

[extruder]
step_pin = PD6
dir_pin = !PD3
enable_pin = !PB3
rotation_distance = 9
microsteps = 16
nozzle_diameter = 0.400
filament_diameter = 1.750
heater_pin = PC3
sensor_type = EPCOS 100K B57560G104F
sensor_pin = PC1
control = pid
pid_kp = 14.529
pid_ki = 0.557
pid_kd = 94.802
min_extrude_temp = 180
min_temp = 0
max_temp = 260

[heater_bed]
heater_pin = PA0
sensor_type = EPCOS 100K B57560G104F
sensor_pin = PC0
control = pid
pid_kp = 325.10
pid_ki = 63.35
pid_kd = 417.10
min_temp = 0
max_temp = 150

[fan]
pin = PB1
kick_start_time = 0.200

[virtual_sdcard]
path = ~/gcode_files

[display_status]

[pause_resume]

[gcode_macro START_PRINT]
gcode = 

[gcode_macro END_PRINT]
gcode = 
	SET_GCODE_OFFSET Z_ADJUST=0

[gcode_macro PAUSE]
rename_existing = BASE_PAUSE
gcode = 
	SAVE_GCODE_STATE NAME=PAUSE_state
	BASE_PAUSE
	G91
	G1 E-{E} F2100
	G1 Z{Z}
	G90
	G1 X{X} Y{Y} F6000

[gcode_macro RESUME]
rename_existing = BASE_RESUME
gcode = 
	G91
	G1 E{E} F2100
	G90
	RESTORE_GCODE_STATE NAME=PAUSE_state MOVE=1
	BASE_RESUME

[gcode_macro CANCEL_PRINT]
rename_existing = BASE_CANCEL_PRINT
gcode = 
	TURN_OFF_HEATERS
	CLEAR_PAUSE
	SDCARD_RESET_FILE
	BASE_CANCEL_PRINT
=======================
Delta max build height 370.00mm (radius tapered above 337.99mm)
Delta max build radius 130.00mm (moves slowed past 135.64mm and 146.20mm)
Extruder max_extrude_ratio=0.266081
mcu 'mcu': Starting serial connect
mcu 'mcu': Unable to open serial port: [Errno 2] could not open port /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0'
webhooks client 1969304600: New connection
webhooks client 1969304600: Client info {'program': 'Moonraker', 'version': 'v0.7.1-41-g2450534'}
mcu 'mcu': Unable to open serial port: [Errno 2] could not open port /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0'
mcu 'mcu': Unable to open serial port: [Errno 2] could not open port /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0'
mcu 'mcu': Unable to open serial port: [Errno 2] could not open port /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0'
mcu 'mcu': Unable to open serial port: [Errno 2] could not open port /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0'
mcu 'mcu': Unable to open serial port: [Errno 2] could not open port /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0'
mcu 'mcu': Unable to open serial port: [Errno 2] could not open port /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0'
mcu 'mcu': Unable to open serial port: [Errno 2] could not open port /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0'
mcu 'mcu': Unable to open serial port: [Errno 2] could not open port /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0'
mcu 'mcu': Unable to open serial port: [Errno 2] could not open port /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0'
mcu 'mcu': Unable to open serial port: [Errno 2] could not open port /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0'
mcu 'mcu': Unable to open serial port: [Errno 2] could not open port /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0'
mcu 'mcu': Unable to open serial port: [Errno 2] could not open port /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0'
mcu 'mcu': Unable to open serial port: [Errno 2] could not open port /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0'
mcu 'mcu': Unable to open serial port: [Errno 2] could not open port /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0'
mcu 'mcu': Unable to open serial port: [Errno 2] could not open port /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0'
mcu 'mcu': Unable to open serial port: [Errno 2] could not open port /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0'
mcu 'mcu': Unable to open serial port: [Errno 2] could not open port /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0'
MCU error during connect
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/klippy.py", line 158, in _connect
    self.send_event("klippy:mcu_identify")
  File "/home/pi/klipper/klippy/klippy.py", line 248, in send_event
    return [cb(*params) for cb in self.event_handlers.get(event, [])]
  File "/home/pi/klipper/klippy/mcu.py", line 765, in _mcu_identify
    raise error(str(e))
error: mcu 'mcu': Unable to connect
Build file /home/pi/klipper/klippy/../.config(2497): Sun Nov  7 20:48:23 2021
========= Last MCU build config =========
CONFIG_LOW_LEVEL_OPTIONS=y
# CONFIG_MACH_AVR is not set
# CONFIG_MACH_ATSAM is not set
# CONFIG_MACH_ATSAMD is not set
# CONFIG_MACH_LPC176X is not set
CONFIG_MACH_STM32=y
# CONFIG_MACH_RP2040 is not set
# CONFIG_MACH_PRU is not set
# CONFIG_MACH_LINUX is not set
# CONFIG_MACH_SIMU is not set
CONFIG_BOARD_DIRECTORY="stm32"
CONFIG_MCU="stm32f103xe"
CONFIG_CLOCK_FREQ=72000000
CONFIG_SERIAL=y
CONFIG_FLASH_START=0x8007000
CONFIG_FLASH_SIZE=0x10000
CONFIG_RAM_START=0x20000000
CONFIG_RAM_SIZE=0x5000
CONFIG_STACK_SIZE=512
CONFIG_STM32_SELECT=y
CONFIG_MACH_STM32F103=y
# CONFIG_MACH_STM32F207 is not set
# CONFIG_MACH_STM32F401 is not set
# CONFIG_MACH_STM32F405 is not set
# CONFIG_MACH_STM32F407 is not set
# CONFIG_MACH_STM32F429 is not set
# CONFIG_MACH_STM32F446 is not set
# CONFIG_MACH_STM32F031 is not set
# CONFIG_MACH_STM32F042 is not set
# CONFIG_MACH_STM32F070 is not set
# CONFIG_MACH_STM32F072 is not set
# CONFIG_MACH_STM32H750 is not set
CONFIG_MACH_STM32F1=y
CONFIG_HAVE_STM32_USBFS=y
CONFIG_HAVE_STM32_CANBUS=y
# CONFIG_STM32_FLASH_START_2000 is not set
# CONFIG_STM32_FLASH_START_5000 is not set
CONFIG_STM32_FLASH_START_7000=y
# CONFIG_STM32_FLASH_START_8000 is not set
# CONFIG_STM32_FLASH_START_8800 is not set
# CONFIG_STM32_FLASH_START_10000 is not set
# CONFIG_STM32_FLASH_START_800 is not set
# CONFIG_STM32_FLASH_START_4000 is not set
# CONFIG_STM32_FLASH_START_0000 is not set
CONFIG_STM32_CLOCK_REF_8M=y
# CONFIG_STM32_CLOCK_REF_12M is not set
# CONFIG_STM32_CLOCK_REF_16M is not set
# CONFIG_STM32_CLOCK_REF_25M is not set
# CONFIG_STM32_CLOCK_REF_INTERNAL is not set
CONFIG_CLOCK_REF_FREQ=8000000
CONFIG_STM32F0_TRIM=16
# CONFIG_STM32_USB_PA11_PA12 is not set
# CONFIG_STM32_SERIAL_USART1 is not set
# CONFIG_STM32_SERIAL_USART1_ALT_PB7_PB6 is not set
# CONFIG_STM32_SERIAL_USART2 is not set
# CONFIG_STM32_SERIAL_USART2_ALT_PD6_PD5 is not set
CONFIG_STM32_SERIAL_USART3=y
# CONFIG_STM32_SERIAL_USART3_ALT_PD9_PD8 is not set
# CONFIG_STM32_CANBUS_PA11_PA12 is not set
# CONFIG_STM32_CANBUS_PB8_PB9 is not set
CONFIG_CANBUS_FREQUENCY=500000
CONFIG_SERIAL_BAUD=250000
CONFIG_USB_VENDOR_ID=0x1d50
CONFIG_USB_DEVICE_ID=0x614e
CONFIG_USB_SERIAL_NUMBER_CHIPID=y
CONFIG_USB_SERIAL_NUMBER="12345"
CONFIG_INITIAL_PINS=""
CONFIG_HAVE_GPIO=y
CONFIG_HAVE_GPIO_ADC=y
CONFIG_HAVE_GPIO_SPI=y
CONFIG_HAVE_GPIO_I2C=y
CONFIG_HAVE_GPIO_HARD_PWM=y
CONFIG_HAVE_GPIO_BITBANGING=y
CONFIG_HAVE_STRICT_TIMING=y
CONFIG_HAVE_CHIPID=y
CONFIG_HAVE_STEPPER_BOTH_EDGE=y
CONFIG_INLINE_STEPPER_HACK=y
=======================
Build file /home/pi/klipper/klippy/../out/klipper.dict(6839): Sun Nov  7 20:49:03 2021
Last MCU build version: v0.10.0-113-gd4aee4f5
Last MCU build tools: gcc: (15:7-2018-q2-6) 7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907] binutils: (2.31.1-11+rpi1+11) 2.31.1
Last MCU build config: BUS_PINS_i2c1=PB6,PB7 RECEIVE_WINDOW=192 RESERVE_PINS_serial=PB11,PB10 BUS_PINS_i2c2=PB10,PB11 BUS_PINS_i2c1a=PB8,PB9 STEPPER_BOTH_EDGE=1 SERIAL_BAUD=250000 ADC_MAX=4095 BUS_PINS_spi3=PB4,PB5,PB3 BUS_PINS_spi2=PB14,PB15,PB13 BUS_PINS_spi1=PA6,PA7,PA5 PWM_MAX=255 MCU=stm32f103xe STATS_SUMSQ_BASE=256 BUS_PINS_spi1a=PB4,PB5,PB3 CLOCK_FREQ=72000000
Build file /home/pi/klipper/klippy/../out/klipper.elf(251836): Sun Nov  7 20:49:17 2021
`

**Comment by conlank** [comment]
From your log it looks like you might need to redo the steps in [here](https://github.com/CobraPi/Klipper-Firmware-FLSUN-QQ-S-Pro-Delta-Printer#step-3----connecting-the-printer-to-the-raspberry-pi). Specifically the one's about setting up the serial ID. The move out of range at the top makes sense because the delta is allowed to move in a shape that is toped with a cone, so the highest point (Z=370) means you are stuck at X,Y of 0,0. Try moving lower before moving in the X and Y.

**Comment by CobraPi** [comment]
I also noticed that you left some parameters suck as the position endstops, arm length, and homing speed (not that important). However, if your delta arms are set at an arbitrary value, that could cause uneven homing of each axis. 

According to your log, it seems like your microcontroller is having trouble establishing a serial connection to the Pi. 

I'd look into possibly try to reflash it agaihn

**Comment by chilledflo** [comment]
Unfortunatly Im having the same issue on my qq-s pro. Any Solutions came up?

**Comment by conlank** [comment]
To me, it looks like the arms and end-stops are set to the default lengths. This can cause issues with movement not being true to reality. Also, extreme movements like @mifrendjim showed in his error (X0, Y10, Z370) _are_ outside of the movement area, so this error is not an error that is possible to fix. 

My recommendation is to run probe_calibrate and then delta_calibrate. Make sure your probe is attached and plugged in.
